In [40]:
import numpy as np
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])

print("A =\n", A)
print("B",B)
print("Ax = B")
x = np.linalg.solve(A, B)
print("x = ", x)
print("")
print("Преверям:")
print("Ax =", A.dot(x))
print("")

A1 = np.linalg.inv(A)
print(A1)
print ("det = ",np.linalg.det(A))
print(np.dot(A1,B))

A =
 [[1 2 3]
 [4 0 6]
 [7 8 9]]
B [12  2  1]
Ax = B
x =  [-9.2         0.9         6.46666667]

Преверям:
Ax = [ 12.   2.   1.]

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]
det =  60.0
[-9.2         0.9         6.46666667]


In [32]:
import numpy as np
A = np.array([[1, 2, -1], [3, -4, 0], [8, -5, 2],[2,0,-5],[11,4,-7]])
B = np.array([1, 7, 12, 7, 15])
print(A)
print (B)
x,residuals,rank,s = np.linalg.lstsq(A,B)
print ("Псевдо решение x = ", x)
print ("Отклонение = ", residuals)
print ("Ранг матрицы = ", rank)
print ("Невязка = ", np.dot(A,x)-B)

[[ 1  2 -1]
 [ 3 -4  0]
 [ 8 -5  2]
 [ 2  0 -5]
 [11  4 -7]]
[ 1  7 12  7 15]
Псевдо решение x =  [ 1.13919353 -0.90498444 -0.9009803 ]
Отклонение =  [ 0.71523211]
Ранг матрицы =  3
Невязка =  [-0.76979505  0.03751834 -0.16349019 -0.21671145  0.21805313]


In [44]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[12, 2, 1]])
C = np.c_[A,B.T]
print (C)
print ("Ранг матрицы A = ", np.linalg.matrix_rank(A))
print ("Ранг дополненной матрицы  = ", np.linalg.matrix_rank(C))
if (np.linalg.matrix_rank(A) != np.linalg.matrix_rank(C)):
    print ("Система не имеет решений")


[[ 1  2  3 12]
 [ 4  5  6  2]
 [ 7  8  9  1]]
Ранг матрицы A =  2
Ранг дополненной матрицы  =  3
Система не имеет решений


In [50]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([3, 2, 1])
C = np.c_[A,B.T]
print (C)
print ("Ранг матрицы A = ", np.linalg.matrix_rank(A))
print ("Ранг дополненной матрицы  = ", np.linalg.matrix_rank(C))
if (np.linalg.matrix_rank(A) != np.linalg.matrix_rank(C)):
    print ("Система не имеет решений")
else:
    y = np.linalg.solve(A,B)
    print ("Решение x =",y)
    print (np.dot(A,y))

[[1 2 3 3]
 [4 5 6 2]
 [7 8 9 1]]
Ранг матрицы A =  2
Ранг дополненной матрицы  =  2
Решение x = [ -9.66666667  15.33333333  -6.        ]
[ 3.  2.  1.]


In [63]:
import numpy as np
import scipy
import scipy.linalg
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
print (A)
P,L,U = scipy.linalg.lu(A)
print ("P = \n", P)
print ("L = \n", L)
print ("U = \n", U)

[[ 1  2  3]
 [ 2 16 21]
 [ 4 28 73]]
P = 
 [[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 1.  0.  0.]]
L = 
 [[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U = 
 [[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]


In [57]:
B = np.array([3, 2, 1])
z = np.linalg.solve(A,B)
print ("Решение x =",z)

Решение x = [ 3.72685185 -0.18287037 -0.12037037]


In [86]:
import numpy as np
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
print(A)
print (B)
x,residuals,rank,s = np.linalg.lstsq(A,B)
print ("Псевдо решение x = ", x)

def Q(x,y,z):
    return (x**2+y**2+z**2)
x = np.linspace(1,2,2001)
#print (x)
f = list(Q(x,(10*x-14),(21*x-29)))
fmin = min(f)
k = f.index(fmin)
print ("Решение при поиске минимальной нормы = ",[x[k],(10*x[k]-14),(21*x[k]-29)])

[[ 1  2 -1]
 [ 8 -5  2]]
[ 1 12]
Псевдо решение x =  [ 1.38191882 -0.18081181  0.0202952 ]
Решение при поиске минимальной нормы =  [1.3820000000000001, -0.17999999999999972, 0.022000000000002018]


In [100]:
import numpy as np
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q,R = np.linalg.qr(A)
R1=R[:2,:2]
B1=np.dot(Q.T,B)[:2]
print(Q)
print (R)
print(R1)
print (B1)
X1 = list(np.linalg.solve(R1,B1))
X1.append(0)
print ("Псевдо решение x = ", X1)


[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
[[ -8.1240384   -9.6011363  -11.07823419]
 [  0.           0.90453403   1.80906807]
 [  0.           0.           0.        ]]
[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]
[ -1.21860576e+01   1.33226763e-15]
Псевдо решение x =  [1.4999999999999989, 1.4728772825180593e-15, 0]
